// Code generated by cmd/cgo; DO NOT EDIT.

//line /mnt/d/Projects/go/tutorial/go-advanced-programing/ch2-cgo/sum/main.go:1:1
package main

//int sum(int a, int b){return a+b;}
import _ "unsafe"

func main() {
	println(( /*line :7:10*/_Cfunc_sum /*line :7:14*/)(1, 1))
}
