// Code generated by cmd/cgo; DO NOT EDIT.

//line /mnt/d/Projects/go/tutorial/go-advanced-programing/ch2-cgo/sum2/main.go:1:1
package main

//int sum(int a,int b);
import _ "unsafe"

//export sum
func sum(a, b  /*line :7:15*/_Ctype_int /*line :7:20*/)  /*line :7:22*/_Ctype_int /*line :7:27*/ {
	return a + b
}

func main() {}
